### PR TITLE
adding languages

### PR DESCRIPTION
**Pull request by FennyWilriani**
## General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### HTML

- [x] pages besides `/index.html` are stored in `/pages`
- [x] the code is well-formatted
- [x] the HTML is valid
- [x] there are no inline styles (example: `style='color: red;'`)
- [x] there are no `<style>` tags with CSS, all styles are hrefs
- [x] there is no inline JavaScript (example: `onclick='doSomething()'`)
- [x] there are no `<script>` tags with JS, all JS is in an separate file
- [x] `id`s are used for JavaScript only, not for CSS
- [x] semantic tags are used
- [x] spelling and grammar is correct in all site content

### CSS

- [x] the code is well-formatted
- [x] passes all the linting checks

### CODE REVIEW

**Review by alihaidermalik20 — COMMENTED** [review]
it may be better to create another assets folder in the main repo rather than planning. And transfer all the languages pictures there. assets folder in planning contains the design wireframes

**Comment by FennyWilriani** [comment]
Separated asset folder only for the language images? why is it necessary? (just out of curiosity) lol

**Comment by alihaidermalik20** [comment]
I meant not only for languages, but an assets folder for all images that will be used on the home page. Since the assets folder in planning is related to pictures in planning such as design wireframes. And languages images aren't related to planning but the actual website. So the folder can just be called assets not languages assets as it's a common approach of having all images in index.html in one folder

**Comment by FennyWilriani** [comment]
Alright, i will create another asset branch to move the picture outside the planning-asset

**Comment by alihaidermalik20** [comment]
There's no need to create another asset branch is there? I think you can just update this current branch and push it again

**Pull request closed without merging**
